include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]

linter:
  rules:
    prefer_single_quotes: true  
    directives_ordering: true
    curly_braces_in_flow_control_structures: true
    prefer_relative_imports: true
    avoid_init_to_null: true
    prefer_adjacent_string_concatenation: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    use_build_context_synchronously: false
    unintended_html_in_doc_comment: false

