name: flutter_folders_structure
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

#================== PACKAGES ============================================#
dependencies:
  flutter:
    sdk: flutter

  # Utilities packages 
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  lottie: ^3.1.3
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.0
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3

  # State management 
  get: ^4.6.6
  get_storage: ^2.1.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # product specification
  readmore: ^3.0.0
  carousel_slider: ^5.0.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4

  # Code generator for data classes, unions, and cloning.
  freezed: ^3.0.6
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

  # Others
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.7.0


#============== DEV PACKAGES ============================================#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

#============ LOCAL ASSETS ============================================#
  assets:
    - assets/fonts/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/launcher/
    - assets/icons/payment_methods/
    - assets/images/animations/
    - assets/images/app_logos/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/reviews/
    - assets/images/app_logos/
    - assets/logos/
    - assets/vectors/

#============= LOCAL FONTS ============================================#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800
        
        

