// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_folders_structure/test/mocks_data/register_controller.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i4;
import 'package:flutter_folders_structure/modules/authentication/data/repositories/auth_repository.dart'
    as _i2;
import 'package:flutter_folders_structure/modules/authentication/presenter/register/controllers/register_controller.dart'
    as _i5;
import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticationRepository_0 extends _i1.SmartFake
    implements _i2.AuthenticationRepository {
  _FakeAuthenticationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxBool_1 extends _i1.SmartFake implements _i3.RxBool {
  _FakeRxBool_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_2 extends _i1.SmartFake
    implements _i4.TextEditingController {
  _FakeTextEditingController_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_3<T extends _i4.State<_i4.StatefulWidget>>
    extends _i1.SmartFake implements _i4.GlobalKey<T> {
  _FakeGlobalKey_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_4<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RegisterController].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterController extends _i1.Mock
    implements _i5.RegisterController {
  @override
  _i2.AuthenticationRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthenticationRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
        returnValueForMissingStub: _FakeAuthenticationRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i2.AuthenticationRepository);

  @override
  _i3.RxBool get hidePassword => (super.noSuchMethod(
        Invocation.getter(#hidePassword),
        returnValue: _FakeRxBool_1(
          this,
          Invocation.getter(#hidePassword),
        ),
        returnValueForMissingStub: _FakeRxBool_1(
          this,
          Invocation.getter(#hidePassword),
        ),
      ) as _i3.RxBool);

  @override
  _i3.RxBool get privacyPolicy => (super.noSuchMethod(
        Invocation.getter(#privacyPolicy),
        returnValue: _FakeRxBool_1(
          this,
          Invocation.getter(#privacyPolicy),
        ),
        returnValueForMissingStub: _FakeRxBool_1(
          this,
          Invocation.getter(#privacyPolicy),
        ),
      ) as _i3.RxBool);

  @override
  _i4.TextEditingController get firstName => (super.noSuchMethod(
        Invocation.getter(#firstName),
        returnValue: _FakeTextEditingController_2(
          this,
          Invocation.getter(#firstName),
        ),
        returnValueForMissingStub: _FakeTextEditingController_2(
          this,
          Invocation.getter(#firstName),
        ),
      ) as _i4.TextEditingController);

  @override
  _i4.TextEditingController get lastName => (super.noSuchMethod(
        Invocation.getter(#lastName),
        returnValue: _FakeTextEditingController_2(
          this,
          Invocation.getter(#lastName),
        ),
        returnValueForMissingStub: _FakeTextEditingController_2(
          this,
          Invocation.getter(#lastName),
        ),
      ) as _i4.TextEditingController);

  @override
  _i4.TextEditingController get userName => (super.noSuchMethod(
        Invocation.getter(#userName),
        returnValue: _FakeTextEditingController_2(
          this,
          Invocation.getter(#userName),
        ),
        returnValueForMissingStub: _FakeTextEditingController_2(
          this,
          Invocation.getter(#userName),
        ),
      ) as _i4.TextEditingController);

  @override
  _i4.TextEditingController get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _FakeTextEditingController_2(
          this,
          Invocation.getter(#email),
        ),
        returnValueForMissingStub: _FakeTextEditingController_2(
          this,
          Invocation.getter(#email),
        ),
      ) as _i4.TextEditingController);

  @override
  _i4.TextEditingController get phone => (super.noSuchMethod(
        Invocation.getter(#phone),
        returnValue: _FakeTextEditingController_2(
          this,
          Invocation.getter(#phone),
        ),
        returnValueForMissingStub: _FakeTextEditingController_2(
          this,
          Invocation.getter(#phone),
        ),
      ) as _i4.TextEditingController);

  @override
  _i4.TextEditingController get password => (super.noSuchMethod(
        Invocation.getter(#password),
        returnValue: _FakeTextEditingController_2(
          this,
          Invocation.getter(#password),
        ),
        returnValueForMissingStub: _FakeTextEditingController_2(
          this,
          Invocation.getter(#password),
        ),
      ) as _i4.TextEditingController);

  @override
  _i4.GlobalKey<_i4.FormState> get registerFormKey => (super.noSuchMethod(
        Invocation.getter(#registerFormKey),
        returnValue: _FakeGlobalKey_3<_i4.FormState>(
          this,
          Invocation.getter(#registerFormKey),
        ),
        returnValueForMissingStub: _FakeGlobalKey_3<_i4.FormState>(
          this,
          Invocation.getter(#registerFormKey),
        ),
      ) as _i4.GlobalKey<_i4.FormState>);

  @override
  set hidePassword(_i3.RxBool? _hidePassword) => super.noSuchMethod(
        Invocation.setter(
          #hidePassword,
          _hidePassword,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set privacyPolicy(_i3.RxBool? _privacyPolicy) => super.noSuchMethod(
        Invocation.setter(
          #privacyPolicy,
          _privacyPolicy,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set registerFormKey(_i4.GlobalKey<_i4.FormState>? _registerFormKey) =>
      super.noSuchMethod(
        Invocation.setter(
          #registerFormKey,
          _registerFormKey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_4<void>(
          this,
          Invocation.getter(#onStart),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_4<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_4<void>(
          this,
          Invocation.getter(#onDelete),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_4<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i6.Future<void> signup() => (super.noSuchMethod(
        Invocation.method(
          #signup,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Disposer addListener(_i7.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i7.Disposer);

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i8.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Disposer addListenerId(
    Object? key,
    _i7.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i7.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
